spring:
  application.name: account-transactions
  r2dbc:
    url: r2dbc:h2:mem:///account_transactions_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    generate-ddl: true
    connection.factory: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath:schema.sql

logging.level.root: DEBUG
